url: "https://amentv.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/amentv" # the subpath of your site, e.g. /blog
title: "Amen TV" # the name of your site, e.g. ACME Corp.

lang:
  en:
    dir: "ltr"
    name: "en"
  ar:
    dir: "rtl"
    name: "ar"