url: "https://amentv.tv" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Amen TV" # the name of your site, e.g. ACME Corp.

lang:
  en:
    dir: "ltr"
    name: "en"
    home: "/en/"
    display: "English"
  ar:
    dir: "rtl"
    name: "ar"
    home: "/"
    display: "Arabic"